### ISSUE TITLE
Call to undefined function Tokolabs\Modules\Console\Generators\str_slug() 

### ISSUE THREAD

**Issue by karneaud** [faisalrizal/modules#10]
Trying to use your package with

> Laravel Framework Lumen (7.1.3) (Laravel Components ^7.0)
> PHP 7.4.19

and ran into the subject error... here is the stack trace.

> [2021-05-11 04:41:45] local.ERROR: Error: Call to undefined function Tokolabs\Modules\Console\Generators\str_slug() in /var/vendor/faisalrizal/modules/src/Console/Generators/MakeModuleCommand.php:70
> Stack trace:
> #0 [internal function]: Tokolabs\Modules\Console\Generators\MakeModuleCommand->handle()
> #1 /var/vendor/illuminate/container/BoundMethod.php(33): call_user_func_array(Array, Array)
> #2 /var/vendor/illuminate/container/Util.php(36): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
> #3 /var/vendor/illuminate/container/BoundMethod.php(91): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
> #4 /var/vendor/illuminate/container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod(Object(Laravel\Lumen\Application), Array, Object(Closure))
> #5 /var/vendor/illuminate/container/Container.php(592): Illuminate\Container\BoundMethod::call(Object(Laravel\Lumen\Application), Array, Array, NULL)
> #6 /var/vendor/illuminate/console/Command.php(134): Illuminate\Container\Container->call(Array)
> #7 /var/vendor/symfony/console/Command/Command.php(258): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
> #8 /var/vendor/illuminate/console/Command.php(121): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
> #9 /var/vendor/symfony/console/Application.php(911): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #10 /var/vendor/symfony/console/Application.php(264): Symfony\Component\Console\Application->doRunCommand(Object(Tokolabs\Modules\Console\Generators\MakeModuleCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #11 /var/vendor/symfony/console/Application.php(140): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #12 /var/vendor/illuminate/console/Application.php(93): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #13 /var/vendor/laravel/lumen-framework/src/Console/Kernel.php(116): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #14 /var/www/artisan(35): Laravel\Lumen\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #15 {main} {"exception":"[object] (Error(code: 0): Call to undefined function Tokolabs\\Modules\\Console\\Generators\\str_slug() at /var/vendor/faisalrizal/modules/src/Console/Generators/MakeModuleCommand.php:70)
> [stacktrace]
> #0 [internal function]: Tokolabs\\Modules\\Console\\Generators\\MakeModuleCommand->handle()
> #1 /var/vendor/illuminate/container/BoundMethod.php(33): call_user_func_array(Array, Array)
> #2 /var/vendor/illuminate/container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
> #3 /var/vendor/illuminate/container/BoundMethod.php(91): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
> #4 /var/vendor/illuminate/container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Laravel\\Lumen\\Application), Array, Object(Closure))
> #5 /var/vendor/illuminate/container/Container.php(592): Illuminate\\Container\\BoundMethod::call(Object(Laravel\\Lumen\\Application), Array, Array, NULL)
> #6 /var/vendor/illuminate/console/Command.php(134): Illuminate\\Container\\Container->call(Array)
> #7 /var/vendor/symfony/console/Command/Command.php(258): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
> #8 /var/vendor/illuminate/console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
> #9 /var/vendor/symfony/console/Application.php(911): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
> #10 /var/vendor/symfony/console/Application.php(264): Symfony\\Component\\Console\\Application->doRunCommand(Object(Tokolabs\\Modules\\Console\\Generators\\MakeModuleCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
> #11 /var/vendor/symfony/console/Application.php(140): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
> #12 /var/vendor/illuminate/console/Application.php(93): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
> #13 /var/vendor/laravel/lumen-framework/src/Console/Kernel.php(116): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
> #14 /var/www/artisan(35): Laravel\\Lumen\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
> #15 {main}
> "}

**Comment by mrfaisalrizal** [comment]
String and Array Helpers have been removed from Core Framework
So if if You need to still use the helper install the package

**composer require laravel/helpers**
